chore: cleanup chart (#71)
* chore: cleanup chart

* chore: regenerate manifests

* manager -> operator

* fix chart appVersion setting

* make regen-manifests fail if manifests are regenerated

---------

Co-authored-by: botthebuilder25[bot] <200541989+botthebuilder25[bot]@users.noreply.github.com>

diff --git a/.github/workflows/regenerate-manifests.yml b/.github/workflows/regenerate-manifests.yml
--- a/.github/workflows/regenerate-manifests.yml
+++ b/.github/workflows/regenerate-manifests.yml
@@ -55,4 +55,6 @@ jobs:
             git add -A
             git commit -m "chore: regenerate manifests"
             git push
+            echo "::error::Manifests were out of date and have been regenerated. Failing to prevent duplicate CI runs."
+            exit 1
           fi
